### ISSUE TITLE
Does not build on ubuntu

### ISSUE THREAD

**Issue by marcusklaas** [japaric/termios.rs#3]
I run into the following error:

```
failed to run custom build command for `termios v0.0.0 (file:///home/marcus/rust/termios.rs)`
Process didn't exit successfully: `/home/marcus/rust/termios.rs/target/build/termios-15d1c7c8305a8ca0/build-script-build` (status=11)
```

**Comment by japaric** [comment]
I think `rust-bindgen` recently reverted back to dynamic linking to LLVM by default, that's likely the cause of the error that you are seeing.

Right now `rust-bindgen` is not building with the latest nightly, once that gets fixed upstream I'll take a look into this issue.

**Comment by japaric** [comment]
I send a [PR](https://github.com/crabtw/rust-bindgen/pull/181) to rust-bindgen updating to the latest nightly, and also switched to my fork that statically links to libclang. Can you try using master? (The travis build passed)

**Comment by marcusklaas** [comment]
Sorry for my late response. I've pulled master, but get the following error messages when compiling:

```
/usr/bin/ld: cannot find -lLLVMBitReader
/usr/bin/ld: cannot find -lLLVMCore
/usr/bin/ld: cannot find -lLLVMLTO
/usr/bin/ld: cannot find -lLLVMLinker
```

and about 20 more like them..

**Comment by japaric** [comment]
Do you have the `libclang-3.5-dev` and `llvm-3.5-dev` packages installed? They are required for the `bindgen` dependency. (The [.travis.yml](https://github.com/japaric/termios.rs/blob/master/.travis.yml) has instructions on how to install them on Ubuntu 12.04).

**Comment by marcusklaas** [comment]
Yup, I do. This problem most likely just something I caused myself, so I'll close this issue. Thanks for the help though!

**Comment by marcusklaas** [comment]
I finally got it to work by the way :fireworks:

**Comment by niihelium** [comment]
@marcusklaas how did you managed this?

**Comment by marcusklaas** [comment]
Sorry, I truly have no idea any more. I am super disappointed to find out I was (am?) one of those people that report that they have fixed something, but not *how*.
